DEFAULT: &DEFAULT
  session_key:    _quails_session
  session_secret: 81f0a99b09d87d45f17f8de5cd2d5b727d598fe080a07bc416df6d8add308bb540df9a431594a3d9ee27f2975f151463c2c297751c1198aa839e38b0555c2953
  admin_dashboard: dashboard

OPEN: &OPEN
  open_access:    true

SAFE: &SAFE
  open_access:    false
  admin_username: admin
  admin_password:  # enter http authentication password here
  admin_session_ask: are_you_admin
  admin_session_reply: Yes,_of_course! # You may change this to something completely different

development:
  <<: *DEFAULT
  <<: *OPEN

production:
  <<: *OPEN # to protect Admin pages with HTTP auth change 'OPEN' to 'SAFE' and update admin_username and password
  session_key:    _quails_session
  # session_secret is not set: it will be generated
  admin_dashboard: dashboard # you may change this

test: &TEST
  <<: *DEFAULT
  open_access:    false
  admin_username: admin
  admin_password:  secret2pwd
  admin_session_ask: are_you_admin
  admin_session_reply: Yes,_of_course!

cucumber:
  <<: *TEST