DEFAULT: &DEFAULT
  number_of_posts: 15

development:
  <<: *DEFAULT
  site_header: birdwatch.org.ua

production:
  <<: *DEFAULT
  site_header: quails.proj

test: &TEST
  <<: *DEFAULT
  site_header: birdwatch.org.ua

cucumber:
  <<: *TEST

