<%
rerun = File.file?('rerun.txt') ? IO.read('rerun.txt') : ""
rerun_opts = rerun.to_s.strip.empty? ? "--format progress features" : "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} #{rerun}"
std_opts = "#{rerun_opts} --format rerun --out rerun.txt --strict --tags ~@wip"
%>
default: --format progress features --strict
rerun: <%= std_opts %> # If using in RubyMine do not attach test runner UI to Cucumber - it will use default profile
wip: --tags @wip:3 --wip features
